### ISSUE TITLE
Cursor movement causes automatic logout

### ISSUE THREAD

**Issue by samtrek** [loserMcloser/waylogout#21]
Cursor movement causes automatic logout in a dual monitor setup, not applicable with a single monitor (a laptop)

**Comment by loserMcloser** [comment]
When I connect the HDMI out on my laptop to my TV, I don't see this issue --- I can move my mouse around and hovering over an action (on either display) causes it to be highlighted on both displays. Everything pretty much works as expected, though there is some glitchy-ness where sometimes one display is updated but the other is not in response to keyboard input.

What do you mean by "automatic logout" --- does the app close immediately, or is the logout action immediately activated? Are you running with the `default-action` set?

Can you try running from a terminal with the example command from [README.md](https://github.com/loserMcloser/waylogout/blob/mainline/README.md) ?  What is the output in the terminal after the app closes?

**Comment by samtrek** [comment]
My own setup is a desktop with two monitors connected, I used the example you recommended in the example, it also resulted in the auto logout from the window manager (hyprland) into the display manager, all info from the terminal was lost due to automatic logout on cursor movement. Could we write the debug to an output, through this we may find out what is going on, or the problem is coming from my own set up.

**Comment by samtrek** [comment]
Yes the automatic logout occurs in hyprland and not in sway, further testing maybe required in hyprland if it is to be used in hyprland, if not the documentation should state compatible window manager. Thank you for the good work.

**Comment by loserMcloser** [comment]
So I installed hyprland and tried it out. Even without a second display attached, when I move the mouse in waylogout it actually causes hyprland itself to crash (which has the side effect of logging the user out). Is this what happens for you? You can test this by logging in through a TTY and launching `hyprland` manually instead of logging in through your display manager.

Then again, for me hyprland also segfaults just by exiting normally with Super+M ....

So seems like it might be a hyprland bug. According to the [Archlinux wiki](https://wiki.archlinux.org/title/Hyprland), Hyprland switched from wlroots to aquamarine as its rendering library, maybe it has something to do with that.

You should have some Hyprland crash reports related to this in `~/.cache/hyprland/` that you can submit to the Hyprland project if you think they should know.

**Comment by samtrek** [comment]
Yes you are right, I tested swaylock-effects on hyprland, it did not work when blurring is applied, probably auto crashing like you mentioned above, but the normal swaylock-effects without blurring works just like the swaylock.
